[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Burningkeys"
version = "2024.12.9"
authors = [
  { name="GÃ¼nthner" },
]
description = "Turns any text any editor into a super customisable editor (by allowing to set global hotkeys)"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Environment :: Console"
]
dependencies = [
    "keyboard>=0.13.0",

]
keywords=["Vim","Hotkeys","Coding"]

[project.scripts]
bkeys = "burningkeys:command_entry_point"