[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.isort]
profile = "black"

[project]
name = "tikzplotlib-patched"
authors = [
  { name = "Nico SchlÃ¶mer", email = "nico.schloemer@gmail.com" },
  { "name" = "Jason Gross", "email" = "jgross@mit.edu" },
]
description = "Convert matplotlib figures into TikZ/PGFPlots.  Version of tikzplotlib patched with additional patches."
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Framework :: Matplotlib",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Topic :: Multimedia :: Graphics :: Graphics Conversion",
  "Topic :: Scientific/Engineering :: Visualization",
]
keywords = ["latex", "tikz", "matplotlib", "graphics"]
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = ["matplotlib >= 1.4.0", "numpy", "Pillow", "webcolors"]

[project.optional-dependencies]
dev = ["seaborn"]

[project.urls]
Code = "https://github.com/JasonGross/tikzplotlib"
Issues = "https://github.com/JasonGross/tikzplotlib/issues"
Funding = "https://github.com/sponsors/nschloe"

[tool.flit.module]
name = "tikzplotlib"