[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "at_common_tasks"
version = "1.0.3"
authors = [
    { name="Rui Chen", email="apextrader.ai@gmail.com" },
]
description = "A Python package providing common asynchronous task definitions and utilities for workflow operations."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "at_common_workflow>=1.1.15"
]

[project.urls]
"Homepage" = "https://github.com/apex-trader/at-common-tasks"
"Bug Tracker" = "https://github.com/apex-trader/at-common-tasks/issues"

[tool.setuptools]
package-dir = {"" = "src"}
packages = [
    "at_common_tasks",
    "at_common_tasks.tasks"
]
