[project]
name = "TolMate"
version = "1.0.0005"
authors = [
  { name="Samuele Giani", email="samuele.giani@empa.ch" }
]
description = "TolMate ;-P"

readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://pypi.org/project/tolmate/"
Issues = "https://pypi.org/project/tolmate/"