[build-system]
requires      = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "localvault"
version = "1.0.0"
description = "A command line utility to generate/store random passwords for the given username/key."
readme = "README.md"
authors = [{ name = "Mukul Taneja", email = "mukultaneja91@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["encryption", "password-generator", "CLI utility"]
dependencies = [
    "click",
    "sqlalchemy",
    "cryptography",
    "prettytable"
]
requires-python = ">=3.6"

[project.urls]
Homepage = "https://github.com/mukultaneja/crypter"

[project.scripts]
localvault = "crypter:main"


