source:
  source_name: periscope
  stream_name: charts
  max_iterations: 20
  workspace_name: MY_WORKSPACE_NAME
  client_site_id: 99999
  database_id: 999
  authentication:
    type: cookies
    params:
      cookies:
        periscope_session: ooooooooo
        cf_bm: kkkkkkkk

backend:
  type: sqlite_in_memory
  database: NOT_USED_WITH_SQLITE
  schema: NOT_USED_WITH_SQLITE
  syncCursorInDBEvery: 2

consumer:
  enabled: true
  name: bigquery

pipeline:
  log_level: DEBUG
