[tool.poetry]
name = "windbot-pylib"
version = "0.2.0"
description = ""
authors = ["Dillan Hildebrand <dillan.hildebrand@protonmail.com>"]
readme = "README.md"
packages = [{include = "windbot_pylib", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.36"
geoalchemy2 = "^0.16.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
