[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"


[project]
name = "eywa-client"
authors = [{name = "Robert Gersak", email = "robi@neyho.com"}]
readme = "README.md"
license = {text = "MIT"}
classifiers = ["License :: OSI Approved :: MIT License"]
version = "0.2.2"
description = "A powerful module for managing async workflows and data processing."
dependencies = [
  "nanoid>=2.0.0"
]


[tool.flit.module]
name = "eywa"
source-directory = "src"


[tool.flit.sdist]
exclude = ["examples", ".DS_Store", "eywa.edn", "robotics.graphql", "dist"]
