[tool.poetry]
name = "PipeX"
version = "0.1.0"
description = "The Data Pipeline Manager CLI is a command-line tool designed to automate and manage ETL (Extract, Transform, Load) workflows. These workflows are critical in data engineering for moving data from one system to another while applying transformations to make the data more useful."
authors = ["ImCYMBIOT <agniveshkumar15@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
typer = "0.15.1"
pandas = "2.2.3"
SQLAlchemy = "2.0.36"
boto3 = "1.35.74"
requests = "2.32.3"
pyyaml = "6.0.2"
tqdm = "4.67.1"
cachetools = "5.5.0"
python-dotenv = "1.0.1"
attrs = "24.2.0"
black = "24.10.0"
blinker = "1.9.0"
botocore = "1.35.76"
build = "1.2.2.post1"
cachecontrol = "0.14.1"
certifi = "2024.8.30"
charset-normalizer = "3.4.0"
cleo = "2.1.0"
click = "8.1.7"
colorama = "0.4.6"
crashtest = "0.4.1"
distlib = "0.3.9"
dnspython = "2.7.0"
docutils = "0.21.2"
dulwich = "0.21.7"
fastjsonschema = "2.21.1"
filelock = "3.16.1"
flake8 = "7.1.1"
flask = "3.1.0"
greenlet = "3.1.1"
idna = "3.10"
importlib-metadata = "8.5.0"
iniconfig = "2.0.0"
installer = "0.7.0"
itsdangerous = "2.2.0"
jaraco-classes = "3.4.0"
jinja2 = "3.1.4"
jmespath = "1.0.1"
jsonschema = "4.23.0"
jsonschema-specifications = "2024.10.1"
keyring = "24.3.1"
markdown-it-py = "3.0.0"
markupsafe = "3.0.2"
mccabe = "0.7.0"
mdurl = "0.1.2"
more-itertools = "10.5.0"
msgpack = "1.1.0"
mypy = "1.13.0"
mypy-extensions = "1.0.0"
mysql-connector-python = "9.1.0"
nh3 = "0.2.19"
numpy = "2.1.3"
packaging = "24.2"
pathspec = "0.12.1"
pexpect = "4.9.0"
pkginfo = "1.12.0"
platformdirs = "4.3.6"
pluggy = "1.5.0"
poetry = "1.8.4"
poetry-core = "1.9.1"
poetry-plugin-export = "1.8.0"
prompt-toolkit = "3.0.36"
psycopg2 = "2.9.10"
ptyprocess = "0.7.0"
pycodestyle = "2.12.1"
pyfiglet = "1.0.2"
pyflakes = "3.2.0"
pygments = "2.18.0"
pymongo = "4.10.1"
pyproject-hooks = "1.2.0"
pytest = "8.3.4"
pytest-mock = "3.14.0"
python-dateutil = "2.9.0.post0"
pytz = "2024.2"
pywin32-ctypes = "0.2.3"
questionary = "2.0.1"
rapidfuzz = "3.10.1"
readme-renderer = "44.0"
referencing = "0.35.1"
requests-toolbelt = "1.0.0"
rfc3986 = "2.0.0"
rich = "13.9.4"
rpds-py = "0.22.3"
s3transfer = "0.10.4"
shellingham = "1.5.4"
six = "1.17.0"
tomlkit = "0.13.2"
trove-classifiers = "2024.10.21.16"
twine = "6.0.1"
typing-extensions = "4.12.2"
tzdata = "2024.2"
urllib3 = "2.2.3"
virtualenv = "20.28.0"
wcwidth = "0.2.13"
werkzeug = "3.1.3"
zipp = "3.21.0"

[tool.poetry.group.dev.dependencies]
pytest = "8.3.4"
black = "24.10.0"
flake8 = "7.1.1"
mypy = "1.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
