[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "jelkasim"
version = "1.1.1"
authors = [
  { name="JoÅ¡t Smrtnik", email="jost.smrtnik@gmail.com" },
]
description = "Simulation for jelka."
readme = "PackageREADME.md"
requires-python = ">=3.8"
dependencies = ["numpy", "pygame", "jelka-validator"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
jelkasim = "jelkasim.main:main"

[project.urls]
Homepage = "https://github.com/Jelka-FMF/JelkaSim"
Issues = "https://github.com/Jelka-FMF/JelkaSim/issues"