[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
dependencies = ["requests" ,"pillow", "PyQt6"]

name = "lfy"
version = "0.0.13"
description = "Translation software for read paper"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

authors = [{ name = "yuhldr", email = "yuhldr@qq.com" }]


[project.urls]
"Homepage" = "https://github.com/ldrfy/lfy"
"Bug Tracker" = "https://github.com/ldrfy/lfy/issues"

[project.scripts]
"lfy" = "lfy.qt.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["lfy*"]


[tool.setuptools.package-data]
"lfy" = ["resources/*", "resources/locale/*/LC_MESSAGES/*"]
