
[tool.poetry]
name = "process-time-killer"
version = "0.1.14"
description = "‚è∞ process-time-killer"
authors = ["Andrew A Levin <your.email@example.com>"]
readme = "README.md"
packages = [
    { include = "timekiller", from = "src" }
]


[tool.poetry.dependencies]
python = ">=3.9"

[tool.poetry.scripts]
timekiller = "timekiller.timekiller:main"


[build-system]
requires = ["poetry>=1.1.0"]
build-backend = "poetry.core.masonry.api"


