[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "GAlgoPy"
version = "0.0.1"
authors = [
  { name="Sattar Bayat", email="sattar.bayat@gmail.com" },
]
description = "This package is used to perform genetic algorithms."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Ar4mus/GAlgoPy"
Issues = "https://github.com/pypa/GAlgoPy/issues"