[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "codi-cooperatiu-internal-tools"
version = "0.2.1"
requires-python = ">=3.10"
description = "Codi Cooperatiu internal tools"
dependencies = ["django>=5.0a1"]
readme = "README.md"
keywords = ["django", "forms", "flowbite"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Framework :: Django",
     "Operating System :: OS Independent"
]


[project.urls]
homepage = "https://github.com/codicoop/codi-cooperatiu-internal-tools"
repository = "https://github.com/codicoop/codi-cooperatiu-internal-tools"


[tool.black]
line-length = 119
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 119

[tool.coverage.run]
branch = true

[tool.pytest.ini_options]
django_find_project = false
pythonpath = "."
DJANGO_SETTINGS_MODULE= "tests.test_settings"