[tool.poetry]
name = "tma-authenticator"
version = "v1.2.0.dev23158"
description = "Verifying telegram user token."
authors = ["Pavel Mulin <pavel@tg-shops.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9.0"
fastapi = ">=0.112.2"
aiocache = ">=0.12.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
