[tool.poetry]
name = "iemap-mi"
version = "0.2.5"
description = "A Python module to interact with the IEMAP REST API"
authors = ["Sergio Ferlito <sergio.ferlito@enea.it>"]
readme = "README.md"
packages = [
    { include = "iemap_mi" }
]



[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.27.0"
pydantic = { extras = ["email"], version = "^2.8.2" }
stdiomask = "^0.0.6"


[tool.poetry.dev-dependencies]
sphinx = "^7.3.7"
sphinx_sitemap = "^2.6.0"
sphinx_rtd_theme = "^1.0.0"
sphinx-autodoc-typehints = "^2"


#[tool.poetry.group.dev.dependencies]
[tool.poetry.group.docs.dependencies]
pytest = "^8.2.2"
pytest-asyncio = "^0.23.7"
pandas = "^2.2.2"
tqdm = "^4.66.4"

[project.urls]
"Documentation" = "https://iemap-mi-module.readthedocs.io/en/latest/index.html"
"Source" = "https://github.com/SergioEanX/iemap_mi_module"
"Issues" = "https://github.com/SergioEanX/iemap_mi_module/issues"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
