[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "signal_rs"
description = "A signal analysis library written in Rust"
authors = [{ name = "fabian", email = "fabian.lieb@peptech.de" }]
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.11"
license = "MIT"
dependencies = [
    "pandas==2.2.3",
    "polars==1.16",
    "cffi"
]

[tool.maturin]
name = "signal_rs"
features = ["pyo3/extension-module"]
version = "0.2.12"
description = "A signal analysis library written in Rust"
readme = "README.md"
exclude = [".venv"]