[project]
name = "translation_hub"
version = "0.2.11"
description = "一个集成国内外翻译服务的第三方库，方便开发者快速集成翻译功能"
authors = [
    { name = "PythonImporter", email = "271374667@qq.com" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.10"

[project.urls]
"Homepage" = "https://github.com/271374667/translation_hub"
"Source Code" = "https://github.com/271374667/translation_hub"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.3.4",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["translation_hub"]
