[tool.poetry]
name = "beancounter"
version = "0.1.0"
description = ""
authors = ["Aaron Buchholz <aaronbuchholz22@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
beancount = 'beancounter.cli:main'