[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ndStepwise"
version = "1.0.1"
description = "A package to perform ND Stepwise regression for multiclass problems."
readme = "README.md"
authors = [
    { name="Maxwell Dix-Matthews", email="maxdixmatthews@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
# dependencies = [
#     # List your runtime dependencies here
# ]

[project.urls]
"Homepage" = "https://github.com/maxdixmatthews/multiclass-regression"

[project.scripts]
run_single_datasets = "ndStepwise.run_single_datasets:main"
run_individual_tree = "ndStepwise.run_individual_tree:main"
run_all_possible_trees = "ndStepwise.run_all_possible_trees:main"
run_mnist = "ndStepwise.run_mnist:main"

