
[tool.poetry]
name = "hpcflow-new2"
version = "0.2.0a187"

description = "Computational workflow management"
authors = ["aplowman <adam.plowman@manchester.ac.uk>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "hpcflow" }
]
exclude = ["hpcflow/data/demo_data"]

[tool.poetry.dependencies]
python = ">=3.8,<3.13"
zarr = [
    {version = "^2.16.1", python = "<3.9"},
    {version = "2.17.2", python = ">=3.9"}
]
numpy = [
    {version = "^1.24.4", python = "<3.9"},
    {version = "^1.26.4", python = ">=3.9"},
]
ruamel-yaml = "^0.18.6"
colorama = "^0.4.6"
termcolor = "^1.1.0"
fsspec = "^2022.2.0"
pytest = {version = "^7.2.0", optional = true}
click = "^8.1.3"
msgpack = "^1.0.4"
reretry = "^0.11.8"
psutil = "^5.9.4"
watchdog = "^2.1.9"
paramiko = "^3.2.0"
aiohttp = "^3.8.4"
rich = "^13.4.2"
h5py = "^3.9.0"
valida = "^0.7.5"
requests = "^2.31.0"
platformdirs = "^4.2.1"

[tool.poetry.group.dev.dependencies]
pylint = "^2.12.2"
pytest = "^7.2.0"
commitizen = "^2.20.3"
pre-commit = "^2.16.0"
black = "^22.3.0"
tuna = "^0.5.11"
sphinx = ">=4,<7"
sphinx-click = "^4.4.0"
sphinx-jinja = "^2.0.1"
sphinx-copybutton = "^0.5.0"
sphinx-design = "^0.4.1"
sphinx-togglebutton = "^0.3.2"
pydata-sphinx-theme = "^0.13.3"
ipykernel = "^6.25.1"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pexpect = "^4.8.0"
papermill = "^2.5.0"
ipykernel = "^6.25.1"

[tool.poetry.group.pyinstaller.dependencies]
pyinstaller = "^5.13"

[tool.poetry.extras]
test = ["pytest"]

[tool.poetry.scripts]
hpcflow = 'hpcflow.cli:cli'

[tool.poetry.plugins.pyinstaller40]
hook-dirs = "hpcflow.__pyinstaller:get_hook_dirs"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.0a187"
tag_format = "v$version"
version_files = [ 
    "pyproject.toml:version",
    "hpcflow/_version.py"
]
bump_message = "bump: $current_version â†’ $new_version [skip ci]"

[tool.black]
line-length = 90

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
