[build-system]
requires = [
    "poetry-core>=1.0.0",
    "Cython>=3.0.11",
    "numpy >=1.2.0",
]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "slow-zigzag"
version = "0.3.1"
description = "Zig Zag indicator"
authors = ["hjkim17 <ouiqdmw17@gmail.com>", "pakchu <gus4734@gmail.com>"]
readme = "README.md"
packages = [
    {include = "zigzag"},
    {include = "zigzag_cython"},
]

include = [
    { path = "zigzag/**/*.so", format = "wheel" },
    { path = "zigzag/**/*.pyx" },
    { path = "zigzag/**/*.pyd" },
    { path = "zigzag/**/*.c"   },
]

[tool.poetry.dependencies]
python = "^3.9"
cython = "^3.0.11"
numpy = "^1.2.0"
pandas = "^2.2.3"


[tool.poetry.scripts]
zigzag-build = "build:main"


[tool.poetry.build]
generate-setup-file = false
script = "build.py"
