[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vector-tompy"
description = "Vectors for tompy projects"
version = "2024.12.11.13.50"
requires-python = ">=3.9"
dependencies = ["math_tompy>=2024.8.14.10.35",
                "sympy>=1.13.0"]
authors = [
    { name = "tompy" },
]
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[tool.hatch.build.targets.wheel]
packages = ["src/vector_tompy"]
