[tool.poetry]
name = "euclidean-algorithm"
version = "0.1.3"
description = ""
authors = ["Макс <rumyantsev1m0s1@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numba = "^0.60.0"
twine = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
