[project]
name = "llm-code-executor"
version = "0.1.0"
description = "python code executor tool that takes fuzzy input text to extract and execute code designed for LLM applications"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "astor>0.8.0",
    "loguru>=0.7.2",
]
authors = [
    { name = "Ezzeldeen Mamdouh", email = "ezzaldin_mamdouh_seddik@hotmail.com" }
]

[project.urls]
Repository = "https://github.com/Ezzaldin97/llm_pyexecutor"

[project.optional-dependencies]
huggingface = [
    "huggingface-hub>=0.26.1",
    "python-dotenv>=1.0.1",
]

[tool.uv]
dev-dependencies = [
    "black>=24.4.0",
    "interrogate>=1.7.0",
    "isort>=5.13.0",
    "notebook>=7.2.2",
    "pdoc>=15.0.0",
    "pytest>=8.1.1",
    "ruff>=0.8.0",
]

[tool.ruff]
line-length = 88
src = ["llm_pyexecutor"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "E402"]
"tests/*.py" = ["E402", "E712"]

[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = true
ignore-semiprivate = true
ignore-private = true
ignore-property-decorators = false
ignore-module = true
exclude = ["tests"]

[tool.setuptools.packages.find]
include = ["llm_pyexecutor"]
exclude = ["imgs"]