[project]
name = "ChatGPTWeb"
version = "0.2.45"
description = "ChatGPT PlayWright API"
authors = [
    { name = "nek0us", email = "nekouss@mail.com" },
]
dependencies = [
    "playwright <= 1.43.0",
    "aioconsole",
    "aiohttp",
    "httpx",
    "pillow",
    "filetype",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "GPL3"

[project.urls]
Homepage = "https://github.com/nek0us/ChatGPT"
Repository = "https://github.com/nek0us/ChatGPT"

[build-system]
requires = [
    "pdm-pep517>=0.12.0",
]
build-backend = "pdm.pep517.api"
