[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SimpleFacturaSDK"
version = "1.1.7"
description = "SDK para la integraci贸n con los servicios de SimpleFactura"
readme = "README.md"
authors = [
    { name = "Carlos Perea", email = "pereacarlos685@gmail.com" }
]
license = { text = "MIT" }
keywords = ["dte", "factura", "boleta", "impuestos internos", "factura electr贸nica", "boleta electr贸nica", "documento", "iva", "SII", "documento tributario electr贸nico"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
requires-python = ">=3.6"
dependencies = [
    "aiohttp",
    "requests-toolbelt",
    "pydantic",
    "httpx",
    "requests",
    "python-dotenv",
    "aiofiles"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-asyncio",
    "requests-mock"
]

[tool.setuptools.packages.find]
where = ["."]