[build-system]
requires = ["setuptools>=75.6", "wheel", "Cython>=3.0.8", "numpy>=1.26.3"]
build-backend = "setuptools.build_meta"

[project]
name = "pymatchmaker"
version = "0.1.0"
description = "A package for real-time music alignment"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "Apache 2.0" }
keywords = ["music", "alignment", "midi", "audio"]
authors = [
    { name = "Matchmaker Development Team", email = "carloscancinochacon@gmail.com" },
]
urls = { Homepage = "https://github.com/pymatchmaker/matchmaker" }
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Cython",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Sound/Audio :: MIDI",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "cython>=3.0.8",
    "python-rtmidi>=1.5.8",
    "mido>=1.3.2",
    "numpy>=1.26.3",
    "scipy>=1.11.4",
    "librosa>=0.10.1",
    "partitura>=1.5.0",
    "python-hiddenmarkov>=0.1.3",
    "pyaudio>=0.2.14",
    "pyfluidsynth>=1.3.3",
]

[project.optional-dependencies]
dev = [
    "black>=23.12.1",
    "isort>=5.13.2",
    "pre-commit>=3.6.0",
    "ipython>=8.12.0",
    "pyclean>=3.0.0",
]

platforms = [
    "macos_11_0_arm64",
    "macos_x86_64",
    "linux_x86_64",
]

[tool.setuptools]
py-modules = []

[tool.setuptools.packages.find]
exclude = ["tests"]
