[project]
name = "tvsm-extractor"
version = "1.0.0"
authors = [
  { name="John Hoffer" },
]
description = "Extract TVSM dataset"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "librosa==0.10.2.post1",
  "matplotlib==3.9.3",
  "soundfile==0.12.1",
  "numpy==2.0.2",
]
[project.scripts]
tvsm-extractor = "tvsm_extractor:main_cli"
[project.urls]
Homepage = "https://github.com/tvquizphd/tvsm-extractor"
Issues = "https://github.com/tvquizphd/tvsm-extractor/issues"
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
