[tool.poetry]
name = "spider-py3"
version = "0.1.0.20241202"
description = ""
authors = ["mathewgeola <mathewgeola@163.com>"]
readme = "README.md"
packages = [
    { include = "spiderpy3", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"
httpx = "^0.27.2"
parsel = "^1.9.1"
furl = "^2.1.3"
colorlog = "^6.9.0"
fake-useragent = "^1.5.1"
htmlmin = "^0.1.12"
pyexecjs = "^1.5.1"
py-mini-racer = "^0.6.0"
ujson = "^5.10.0"
aiohttp = "^3.11.2"
pycryptodome = "^3.21.0"
bs4 = "^0.0.2"
opencv-python = "^4.10.0.84"
numpy = "^2.1.3"
pandas = "^2.2.3"
pillow = "^11.0.0"
openpyxl = "^3.1.5"
jsonpath = "^0.82.2"
pika = "^1.3.2"
xlrd = "^2.0.1"
cx-oracle = "^8.3.0"
sqlalchemy = "^2.0.36"
xlwt = "^1.3.0"
redis = "^5.2.0"
tldextract = "^5.1.3"
pymysql = "^1.1.1"
pyyaml = "^6.0.2"
socksio = "^1.0.0"
pymongo = "^4.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
