[project]
name = "anura"
version = "0.0.1"
authors = [
    { name="Xavier Mejia", email="geekpad@anura.io" }
]
description = "Anura SDK for Python"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests",
    "aiohttp"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
Homepage = "https://github.com/anuraio/anura-sdk-python"
Issues = "https://github.com/anuraio/anura-sdk-python/issues"
