[tool.poetry]
name = "ti-analyzer-python"
version = "1.0.4"
description = "Library of analyzers for connection to RT Protect TI product"
authors = ["RT Protect TI"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = ">=2.32.3,<2.33.0"
confluent-kafka = ">=2.4.0,<2.5.0"
pymongo = ">=4.10.1,<4.11.0"
jsonschema = ">=4.23.0,<4.24.0"
pydantic = ">=2.10.2,<2.11.0"


[tool.poetry.group.dev.dependencies]
pycodestyle = ">=2.12.1,<2.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
