[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core>=1.9.0"
]

[tool.black]
extend = "ci/pyproject.toml"

[tool.poetry]
authors = [
  "Alex Kalaverin <alex@kalaver.in>"
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
description = "A comprehensive set of advanced utilities for Python programming, e.g. HTTP communication, string handling, logging enhancements, introspection, dynamic importing, property caching descriptors, data class extensions, serialization, etc."
homepage = "https://kalaver.in"
keywords = [
  "dataclass",
  "decorators",
  "descriptors",
  "http",
  "import",
  "introspection",
  "logging",
  "python",
  "serialization",
  "string",
  "utilities"
]
license = "MIT License"
name = "kalib"
packages = [
  {include = "kalib", from = "src"}
]
readme = "README.md"
version = "0.18.14"

[tool.poetry.dependencies]
gitpython = "^3.1.43"
natsort = "^8.4.0"
orjson = "^3.10.7"
python = "^3.10"
tomli = "^2.0.1"
xxhash = "^3.5.0"
zstd = "^1.5.5.1"

[tool.poetry.dependencies.base2048]
optional = true
version = "^0.1.3"

[tool.poetry.dependencies.charset-normalizer]
optional = true
version = "^3.3.2"

[tool.poetry.dependencies.fake_useragent]
optional = true
version = "^1.5.1"

[tool.poetry.dependencies.feedparser]
optional = true
version = "^6.0.11"

[tool.poetry.dependencies.lxml]
optional = true
version = "^5.3.0"

[tool.poetry.dependencies.msgpack]
optional = true
version = "^1.1.0"

[tool.poetry.dependencies.pre-commit]
optional = true
version = "^3.7.1"

[tool.poetry.dependencies.pydantic]
optional = true
version = "^2.7.4"

[tool.poetry.dependencies.python-magic]
optional = true
version = "^0.4.27"

[tool.poetry.dependencies.pyyaml]
optional = true
version = "^6.0.2"

[tool.poetry.dependencies.setproctitle]
optional = true
version = "^1.3.3"

[tool.poetry.dependencies.versioneer]
optional = true
version = "^0.29"

[tool.poetry.dependencies.yarl]
optional = true
version = "^1.13.1"

[tool.poetry.extras]
all = [
  "base2048",
  "charset-normalizer",
  "fake_useragent",
  "feedparser",
  "lxml",
  "msgpack",
  "pydantic",
  "python-magic",
  "pyyaml",
  "setproctitle",
  "versioneer",
  "yarl"
]
data = [
  "base2048",
  "charset-normalizer",
  "python-magic"
]
deploy = [
  "pre-commit",
  "versioneer"
]
pydantic = [
  "pydantic"
]
pyyaml = [
  "pyyaml"
]
web = [
  "fake_useragent",
  "feedparser",
  "lxml",
  "msgpack",
  "yarl"
]

[tool.ruff]
extend = "ci/pyproject.toml"

[tool.ruff.lint.isort]
known-first-party = [
  "kalib"
]

[tool.versioneer]
VCS = "git"
parentdir_prefix = ""
style = "pep440"
tag_prefix = ""
versionfile_source = "pyproject.toml"

[tool.yamlfix]
line_length = 89
preserve_quotes = false
quote_basic_values = false
quote_representation = "'"
section_whitelines = 1
sequence_style = "block_style"
whitelines = 1
