[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "glowbuzzer-gbp"
version = "0.0.0a6"
description = "glowbuzzer Python API (GBP)"
readme = "README.md"
authors = [
    {name = "glowbuzzer", email = "hello@glowbuzzer.com"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "websockets~=13.1",
    "pydantic~=2.9.2"
]

[project.optional-dependencies]
test = [
    "pytest~=8.3.3",
    "pytest-asyncio~=0.16.0"
]

[tool.setuptools.packages]
find = {where = ["src"]}
