[tool.poetry]
name = "ki2-python-utils"
version = "0.3.1"
description = ""
authors = ["Adrien KERFOURN <ak.sitecontact@gmail.com>"]
readme = "README.md"
packages = [{include = "ki2_python_utils"}]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
typing-extensions = "^4.12.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-asyncio = "^0.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
